### ISSUE TITLE
Unable to use ng-repeat for ion-slide

### ISSUE THREAD

**Issue by niyando** [arielfaur/ionic-wizard#15]
Sorry to bug you again but I am unable to render slides using ng-repeat. the next and prev functionality breaks and both states are disabled after the first step. Check this plunkr
http://plnkr.co/edit/nZirAKqjWgZB2EDiwxR1?p=preview

**Comment by arielfaur** [comment]
Hi @niyando 

Could you please check this plunkr and get back to me? It uses ng-repeat to generate slides. I added conditions to the third slide (first and last name fields must be filled).
http://plnkr.co/edit/qYUBHeLTw6wIVtHrl2d2?p=preview

Could you also check if it works with ng-if?

**Comment by niyando** [comment]
hey, saw your plunkr
ng-repeat does work now. did u change something to make the prev button work? why isnt it working in my plunkr?

**Comment by arielfaur** [comment]
Yes, the ```ion-wizard.js``` is a different version. It seems I'll need to roll back some of the changes I introduced lately, because they do not play well with angular directives. The problem with the current version is that it does not allow placing two directives requesting a new/isolated scope on the same element,  for example: 
```<ion-slide ion-wizard-step ng-repeat="...">```

So in the meantime replace your ion-wizard.js file with the one in the plunkr until I release the fix.

**Comment by niyando** [comment]
makes sense @arielfaur. Thanks for the help! :beer:

**Comment by niyando** [comment]
As for the ng-if, it does work on the part where it should not render the slide but doesn't play nice with ng-repeat as it fails to update the $index property of ng-repeat.

However, I was able to circumvent this using filter inside ng-repeat
```js
ng-repeat="step in page.steps | filter:{skip:'!true'}"
````
no need to ng-if.
